version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - mvn clean install -DskipTests
  build:
    commands:
      - echo "Building the project..."
      - mvn package -DskipTests
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - target/*.jar
  discard-paths: yes

